import datetime
import sqlite_utils
from fec_to_sqlite.utils import save_filing

FILING = {
    "itemizations": {
        "Schedule A": [
            {
                "form_type": "SD10",
                "filer_committee_id_number": "C00600825",
                "transaction_id_number": "SD10.4225",
                "entity_type": "ORG",
                "creditor_organization_name": "Barfield, Murphy, Shank & Smith, LLC",
                "creditor_last_name": "",
                "creditor_first_name": "",
                "creditor_middle_name": "",
                "creditor_prefix": "",
                "creditor_suffix": "",
                "creditor_street_1": "1121 Riverchase Office Road",
                "creditor_street_2": "",
                "creditor_city": "Birmingham",
                "creditor_state": "AL",
                "creditor_zip_code": "35244",
                "purpose_of_debt_or_obligation": "Professional Services - Accounting",
                "beginning_balance_this_period": 120.95,
                "incurred_amount_this_period": 0.0,
                "payment_amount_this_period": 120.95,
                "balance_at_close_this_period": 0.0,
            }
        ],
        "Schedule E": [
            {
                "form_type": "SE",
                "filer_committee_id_number": "C00600825",
                "transaction_id_number": "SE.4287",
                "back_reference_tran_id_number": "",
                "back_reference_sched_name": "",
                "entity_type": "ORG",
                "payee_organization_name": "Bank of Tuscaloosa",
                "payee_last_name": "",
                "payee_first_name": "",
                "payee_middle_name": "",
                "payee_prefix": "",
                "payee_suffix": "",
                "payee_street_1": "P O Box 2508",
                "payee_street_2": "",
                "payee_city": "Tuscaloosa",
                "payee_state": "AL",
                "payee_zip_code": "35403",
                "election_code": "G2016",
                "election_other_description": "",
                "dissemination_date": datetime.datetime(2016, 11, 30, 0, 0),
                "expenditure_amount": 25.0,
                "disbursement_date": datetime.datetime(2016, 11, 30, 0, 0),
                "calendar_y_t_d_per_election_office": 23515.0,
                "expenditure_purpose_descrip": "Bank Service Charges",
                "category_code": "001",
                "payee_cmtte_fec_id_number": "C00600825",
                "support_oppose_code": "O",
                "candidate_id_number": "P80001571",
                "candidate_last_name": "DONALD J. TRUMP FOR PRESIDENT",
                "candidate_first_name": "INC.",
                "candidate_middle_name": "",
                "candidate_prefix": "",
                "candidate_suffix": "",
                "candidate_office": "P",
                "candidate_district": "",
                "candidate_state": "",
                "completing_last_name": "Pate",
                "completing_first_name": "Luther",
                "completing_middle_name": "Stan",
                "completing_prefix": "",
                "completing_suffix": "IV",
                "date_signed": datetime.datetime(2017, 1, 31, 0, 0),
                "memo_code": "",
                "memo_text_description": "",
            }
        ],
    },
    "text": [
        {
            "rec_type": "TEXT",
            "filer_committee_id_number": "C00600825",
            "transaction_id_number": "SD10.4195.TEXT",
            "back_reference_tran_id_number": "SD10.4195",
            "back_reference_sched_form_name": "SD10",
            "text": "(Current loan amount of 21500.00 from a balance of 21500.00 has been forgiven)",
        }
    ],
    "header": {
        "record_type": "HDR",
        "ef_type": "FEC",
        "fec_version": "8.1",
        "soft_name": "FECfile",
        "soft_ver": "8.1.0.6(f30)",
        "report_id": "",
        "report_number": "",
        "comment": "",
    },
    "filing": {
        "form_type": "F3XN",
        "filer_committee_id_number": "C00600825",
        "committee_name": "WeThePeople Foundation",
        "change_of_address": "",
        "street_1": "1301 Industrial Park Drive",
        "street_2": "",
        "city": "Tuscaloosa",
        "state": "AL",
        "zip_code": "35401",
        "report_code": "MYE",
        "election_code": "",
        "date_of_election": "",
        "state_of_election": "",
        "coverage_from_date": datetime.datetime(2016, 11, 29, 0, 0),
        "coverage_through_date": datetime.datetime(2016, 12, 31, 0, 0),
        "qualified_committee": "",
        "treasurer_last_name": "Pate",
        "treasurer_first_name": "Luther",
        "treasurer_middle_name": "Stan",
        "treasurer_prefix": "",
        "treasurer_suffix": "IV",
        "date_signed": datetime.datetime(2017, 1, 31, 0, 0),
        "col_a_cash_on_hand_beginning_period": 78.12,
        "col_a_total_receipts": 1012.03,
        "col_a_subtotal": 1090.15,
        "col_a_total_disbursements": 1090.15,
        "col_a_cash_on_hand_close_of_period": 0.0,
        "col_a_debts_to": 0.0,
        "col_a_debts_by": 0.0,
        "col_a_individuals_itemized": 1012.03,
        "col_a_individuals_unitemized": 0.0,
        "col_a_individual_contribution_total": 1012.03,
        "col_a_political_party_committees": 0.0,
        "col_a_other_political_committees_pacs": 0.0,
        "col_a_total_contributions": 1012.03,
        "col_a_transfers_from_aff_other_party_cmttees": 0.0,
        "col_a_total_loans": 0.0,
        "col_a_total_loan_repayments_received": 0.0,
        "col_a_offsets_to_expenditures": 0.0,
        "col_a_federal_refunds": 0.0,
        "col_a_other_federal_receipts": 0.0,
        "col_a_transfers_from_nonfederal_h3": 0.0,
        "col_a_levin_funds": 0.0,
        "col_a_total_nonfederal_transfers": 0.0,
        "col_a_total_federal_receipts": 1012.03,
        "col_a_shared_operating_expenditures_federal": 0.0,
        "col_a_shared_operating_expenditures_nonfederal": 0.0,
        "col_a_other_federal_operating_expenditures": 0.0,
        "col_a_total_operating_expenditures": 0.0,
        "col_a_transfers_to_affiliated": 0.0,
        "col_a_contributions_to_candidates": 0.0,
        "col_a_independent_expenditures": 1090.15,
        "col_a_coordinated_expenditures_by_party_committees": 0.0,
        "col_a_total_loan_repayments_made": 0.0,
        "col_a_loans_made": 0.0,
        "col_a_refunds_to_individuals": 0.0,
        "col_a_refunds_to_party_committees": 0.0,
        "col_a_refunds_to_other_committees": 0.0,
        "col_a_total_refunds": 0.0,
        "col_a_other_disbursements": 0.0,
        "col_a_federal_election_activity_federal_share": 0.0,
        "col_a_federal_election_activity_levin_share": 0.0,
        "col_a_federal_election_activity_all_federal": 0.0,
        "col_a_federal_election_activity_total": 0.0,
        "col_a_total_federal_disbursements": 1090.15,
        "col_a_total_contributions_refunds": 0.0,
        "col_a_net_contributions": 1012.03,
        "col_a_total_federal_operating_expenditures": 0.0,
        "col_a_total_offsets_to_expenditures": 0.0,
        "col_a_net_operating_expenditures": 0.0,
        "col_b_cash_on_hand_jan_1": 0.0,
        "col_b_year": 2016.0,
        "col_b_total_receipts": 168362.8,
        "col_b_subtotal": 168362.8,
        "col_b_total_disbursements": 168362.8,
        "col_b_cash_on_hand_close_of_period": 0.0,
        "col_b_individuals_itemized": 167822.79,
        "col_b_individuals_unitemized": 540.01,
        "col_b_individual_contribution_total": 168362.8,
        "col_b_political_party_committees": 0.0,
        "col_b_other_political_committees_pacs": 0.0,
        "col_b_total_contributions": 168362.8,
        "col_b_transfers_from_aff_other_party_cmttees": 0.0,
        "col_b_total_loans": 0.0,
        "col_b_total_loan_repayments_received": 0.0,
        "col_b_offsets_to_expenditures": 0.0,
        "col_b_federal_refunds": 0.0,
        "col_b_other_federal_receipts": 0.0,
        "col_b_transfers_from_nonfederal_h3": 0.0,
        "col_b_levin_funds": 0.0,
        "col_b_total_nonfederal_transfers": 0.0,
        "col_b_total_federal_receipts": 168362.8,
        "col_b_shared_operating_expenditures_federal": 0.0,
        "col_b_shared_operating_expenditures_nonfederal": 0.0,
        "col_b_other_federal_operating_expenditures": 0.0,
        "col_b_total_operating_expenditures": 0.0,
        "col_b_transfers_to_affiliated": 0.0,
        "col_b_contributions_to_candidates": 0.0,
        "col_b_independent_expenditures": 168362.8,
        "col_b_coordinated_expenditures_by_party_committees": 0.0,
        "col_b_total_loan_repayments_made": 0.0,
        "col_b_loans_made": 0.0,
        "col_b_refunds_to_individuals": 0.0,
        "col_b_refunds_to_party_committees": 0.0,
        "col_b_refunds_to_other_committees": 0.0,
        "col_b_total_refunds": 0.0,
        "col_b_other_disbursements": 0.0,
        "col_b_federal_election_activity_federal_share": 0.0,
        "col_b_federal_election_activity_levin_share": 0.0,
        "col_b_federal_election_activity_all_federal": 0.0,
        "col_b_federal_election_activity_total": 0.0,
        "col_b_total_federal_disbursements": 168362.8,
        "col_b_total_contributions_refunds": 0.0,
        "col_b_net_contributions": 168362.8,
        "col_b_total_federal_operating_expenditures": 0.0,
        "col_b_total_offsets_to_expenditures": 0.0,
        "col_b_net_operating_expenditures": 0.0,
    },
}


def test_save_filing(tmpdir):
    db_path = str(tmpdir / "data.db")
    db = sqlite_utils.Database(db_path)
    save_filing(FILING, db)
    assert {"itemizations", "filings", "texts"} == set(db.table_names())
